name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Calculate hash of image files
        id: image-hash
        run: |
          echo "IMAGE_HASH=$(find node_modules/.astro/assets -type f -name '*.avif' | xargs cat | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache Images
        uses: actions/cache@v4
        with:
          path: node_modules/.astro/assets
          key: ${{ runner.os }}-images-${{ env.IMAGE_HASH }}
          restore-keys: |
            ${{ runner.os }}-images-

      - name: Check Cache Hit
        run: |
          echo "Cache hit is ${{ steps.cache-images.outputs.cache-hit }}"
          if [ "${{ steps.cache-images.outputs.cache-hit }}" != 'true' ]; then
            echo "Cache miss, need to rebuild assets..."
          else
            echo "Cache hit, using cached assets..."
          fi

      - name: Install, build, and upload your site output
        if: steps.cache-images.outputs.cache-hit != 'true'
        uses: withastro/action@v2
        with:
          node-version: 18.17.1
          package-manager: npm

      - name: Cache is loaded ?
        run: |
          cd node_modules/.astro/assets
          ls

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
